CREATE TABLE [dbo].[Vendas]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Nome] VARCHAR(200) NULL, 
    [Identificacao] BIGINT NULL, 
    [TipoPessoa] VARCHAR(50) NULL, 
    [Sexo] VARCHAR(50) NULL, 
    [TicketMedio] DECIMAL(18, 2) NULL, 
    [UltimaVenda] DATETIME NULL, 
    [ValorTotal] DECIMAL(18, 2) NULL, 
    [ValorItens] DECIMAL(18, 2) NULL, 
    [QtItens] INT NULL, 
    [DataVenda] DATETIME NULL, 
    [IdNf] BIGINT NULL, 
    [Veiculo] VARCHAR(100) NULL, 
    [Ano] VARCHAR(20) NULL, 
    [Placa] VARCHAR(20) NULL, 
    [Km] VARCHAR(20) NULL, 
    [FaixaAno] VARCHAR(50) NULL, 
    [FaixaTicketMedio] VARCHAR(50) NULL, 
    [NomeServico] VARCHAR(200) NULL, 
    [Funcionario] VARCHAR(200) NULL, 
    [QtItensServico] INT NULL, 
    [TempoServico] VARCHAR(20) NULL, 
    [TipoServico] VARCHAR(200) NULL, 
    [ValorTotalServico] DECIMAL(18, 2) NULL, 
    [ValorUnitServico] DECIMAL(18, 2) NULL, 
    [FormaPagto] VARCHAR(100) NULL, 
    [CondPagto] VARCHAR(100) NULL, 
    [Telefone] VARCHAR(200) NULL 
)
